#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

start_service() {
    local enabled

    enabled="$(uci -q get tohsakawrt-tgbot.main.enabled)"
    [ "$enabled" = "1" ] || return 0

    procd_open_instance
    procd_set_param command /usr/bin/tohsakawrt-tgbot
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 0
    procd_set_param stderr 1
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger "tohsakawrt-tgbot"
}
